AWSTemplateFormatVersion: 2010-09-09
Description: ioquake3 server on port 27960
Parameters:
  AmiAlias:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-minimal-hvm-arm64-ebs
    Description: >-
      The actual AMI id ami-xxxxx will be dereferenced based on this alias.
      Default is "Amazon Linux 2 minimal HVM"
  VpcId:
    Type: 'AWS::EC2::VPC::Id'
    Description: >-
      VpcId of your Virtual Private Cloud.  You probably just have one default
      VPC.  Choose it here.
    ConstraintDescription: Must be the VPC Id of an existing Virtual Private Cloud.
  Subnets:
    Type: 'List<AWS::EC2::Subnet::Id>'
    Description: Choose a subnet for the instance.
  KeyName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: >-
      Choose a Key Pair for this instance.  If you do not have one, go make one
      in the EC2 section and it will appear here.
  BucketName:
    Type: 'String'
    Description: >-
      Bucket to hold all the pak files etc. Put region in the name, as a reminder
      that cross region transfer costs do apply so a bucket per region is most
      cost effective.
  Server0Name:
    Type: 'String'
    Description: >-
      Hostname for server on port 27960. The first 20 chars show up in the quake3 UI. OPTIONAL - leaving it empty will not start the server
  Server1Name:
    Type: 'String'
    Description: >-
      Hostname for server on port 27961. The first 20 chars show up in the quake3 UI. OPTIONAL - leaving it empty will not start the server
  RconPassword:
    Type: 'String'
    Description: >-
      Password to access server using RCON
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: >-
        Security Group that allows access to SSH connections and the quake3 server
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:  0.0.0.0/0
        - IpProtocol: udp
          FromPort: 27960
          ToPort: 27962
          CidrIp:  0.0.0.0/0
  ElasticIp:
    Type: AWS::EC2::EIP
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: /
      Roles: 
       - !Ref Ec2InstanceRole
  Ec2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
  InstanceS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ${BucketName}-list-and-get-objects
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${BucketName}/*
              - !Sub arn:aws:s3:::${BucketName}
      Roles:
        -
          !Ref Ec2InstanceRole
  InstanceEIpPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: allocate-elastic-ips
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - ec2:DescribeAddresses
              - ec2:AllocateAddress
              - ec2:DescribeInstances
              - ec2:AssociateAddress
            Resource: '*'
      Roles:
        -
          !Ref Ec2InstanceRole
  AutoScalingGroup:
    Type: 'AWS::AutoScaling::AutoScalingGroup'
    Properties:
      VPCZoneIdentifier: !Ref Subnets
      DesiredCapacity: 0
      MinSize: 0
      MaxSize: 1
      MixedInstancesPolicy:
        InstancesDistribution:
          OnDemandBaseCapacity: 0
          OnDemandPercentageAboveBaseCapacity: 0
          SpotAllocationStrategy: lowest-price
          # This allows up to 6 instance types across 3 AZs (3*6=18)
          SpotInstancePools: 20
        LaunchTemplate:
          LaunchTemplateSpecification: 
            LaunchTemplateId: !Ref LaunchTemplate
            Version: !GetAtt LaunchTemplate.LatestVersionNumber
          Overrides:
            - InstanceType: t4g.nano
            - InstanceType: t4g.micro
      Tags:
        - Key: Name
          Value: Quake3Quest
          PropagateAtLaunch: "true"
  LaunchTemplate:
    Type: 'AWS::EC2::LaunchTemplate'
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files :
            /home/ec2-user/README.md:
              content: !Sub |
                Useful commands:

                sudo less /var/log/cloud-init-output.log
                sudo tail -f /var/log/cloud-init-output.log

                cat /run/systemd/system/quake3@.service
                systemctl status quake3@0
                journalctl -f -u quake3@0

                Config files:
                cat /usr/lib/ioquake3/baseq3/autoexec.cfg
                cat /usr/lib/ioquake3/baseq3/server0.cfg
                cat /usr/lib/ioquake3/baseq3/server1.cfg
                cat /usr/lib/ioquake3/baseq3/ctf.cfg
                cat /usr/lib/ioquake3/baseq3/1x1.cfg
                cat /usr/lib/ioquake3/baseq3/demo.cfg
                cat /usr/lib/ioquake3/baseq3/custom.cfg
                cat /usr/lib/ioquake3/baseq3/custom2.cfg

                Local console:
                icecon 127.0.0.1:27960 "${RconPassword}"

                Remote console:
                quake3-rcon 13.38.149.128 "${RconPassword}"

                Quake rcon commands:
                status
                exec ctf.cfg
                addbot sarge 4 //that last number is the skill level [1-5]. e.g. doom, bones, slash, orbb, keel
                kick 2         //see status for number for each player
                kickbots       //kicks all bots
                vstr d1        //begin map rotation starting with d1 to d19
                map q3dm17
                map_restart
                timelimit 5
                fraglimit 20
                set bot_minplayers 3 //fills gamer list up to this number with bots

                Map list
                - http://www.bosskey.net/q3a/maps/standard.html

                Official ioquake3 admin guide
                - https://ioquake3.org/help/sys-admin-guide/#rcon

                Reference server.cfg
                - https://github.com/MarioVilas/ioquake3-server-docker/blob/master/q3a/baseq3/server.cfg
            /opt/ioquake3/baseq3/autoexec.cfg:
              content: !Sub |
                // This script is automatically run when the server starts.
                // 1. Engine setings
                set vm_game 2
                set vm_cgame 2
                set vm_ui 2
                seta rate "12400"
                seta snaps "40"
                seta cl_packetdup "1"
                set com_hunkmegs 256                     // maximum RAM used by the server
                
                // 2. Server settings
                // Note: net_port and sv_hostname are set in separate cfgs to enable multiple servers per machine
                //
                set sv_master1 "13.36.227.32:27950"      // default is master.ioquake3.org
                set dedicated 2                          // 1: dedicated server, but not announced | 2: dedicated server, announced
                set sv_pure 0                            // 1: pure server, no altered pk3 files
                set g_log server.log                     // log file name
                set logfile 0                            // 0:off 1:buffered 2:continuous 3:append to existing
                set sv_allowDownload 1                   // enables downloading maps from server. Requires clientside config. See https://openarena.fandom.com/wiki/Manual/Automatic_downloading
                set sv_dlURL ""                          // Tell clients to download pk3s from this URL instead of this server. Empty means use this server.
                set sv_dlRate 1024                        // Maximum download rate offered to clients (kb/s)
                set rconpassword "${RconPassword}"
                sets g_needpass 0                        // To set a password set this to 1, and uncomment the sets below
                //sets g_password "my-password"
                
                // 3. Game settings (common across all modes)
                //
                set sv_maxclients 8                      // max. number of clients than can connect
                set g_motd "Enter the Slaughter-Verse!"
                set g_allowvote 1                        // allow players to vote for map changes
                set timelimit 0                          // time limit in minutes for all modes (0 for no limit)
                // Weapon settings
                set g_weaponrespawn 5                    // weapon respawn in seconds
                set g_inactivity 120                     // kick players after being inactive (in seconds)
                set g_forcerespawn 0                     // 0:player has to press primary button to respawn
                // Bot settings
                set bot_enable 1                         // allow bots on the server
                set bot_nochat 1                         // 1: disable bot chatting (recommended!)
                set g_spskill 4                          // default skill of bots [1-5]
                set bot_minplayers 0                     // fills the server with bots to satisfy the minimum
            /opt/ioquake3/baseq3/server0.cfg:
              content: !Sub |
                set sv_hostname "${Server0Name}"
                set net_port 27960
                exec varied.cfg
            /opt/ioquake3/baseq3/server1.cfg:
              content: !Sub |
                set sv_hostname "${Server1Name}"
                set net_port 27961
                exec demo.cfg
            /opt/ioquake3/baseq3/stress.cfg:
              content: !Sub |
                // Useful config options when stress testing the server.
                // These facilitate upping player numbers by joining from PC clients and leaving them idle
                set g_inactivity 0                       // do not kick inactive users
                set g_forcerespawn 1                     // auto respawn
            /opt/ioquake3/baseq3/standard.cfg:
              content: !Sub |
                set g_gametype 0                    //  0       Free for all
                set fraglimit 20                    // frag limit for all modes (0 for no limit)
                set d1 "map q3dm7 ; set nextmap vstr d2"
                set d2 "map q3dm17 ; set nextmap vstr d3"
                set d3 "map q3dm6 ; set nextmap vstr d4"
                set d4 "map q3dm15 ; set nextmap vstr d1"
                
                vstr d1                             // load first map in rotation
            /opt/ioquake3/baseq3/ctf.cfg:
              content: !Sub |
                set g_gametype 4                    //  0       Capture the Flag
                set capturelimit 8                  // capture limit for CTF mode (0 for no limit)
                set g_teamAutoJoin 1                // 0:goes into spectator mode, 1:auto joins a team
                set g_teamForceBalance 1            // 0:free selection, 1:forces player to join weak team
                set g_friendlyFire 1                // 1: friendly fire allowed in CTF mode

                set c1 "map q3ctf1 ; set nextmap vstr c2"
                set c2 "map q3ctf2 ; set nextmap vstr c3"
                set c3 "map q3ctf4 ; set nextmap vstr c1"
                vstr c1                             // load first map in rotation
            /opt/ioquake3/baseq3/1x1.cfg:
              content: !Sub |
                set g_gametype 0                    //  0       Free for all
                set fraglimit 10
                set d1 "map Q3DM2 ; set nextmap vstr d2"
                set d2 "map Q3DM3 ; set nextmap vstr d3"
                set d3 "map Q3DM4 ; set nextmap vstr d4"
                set d4 "map Q3DM5 ; set nextmap vstr d5"
                set d5 "map Q3TOURNEY3 ; set nextmap vstr d6"
                set d6 "map Q3TOURNEY5 ; set nextmap vstr d7"
                set d7 "map Q3TOURNEY6 ; set nextmap vstr d1"
                vstr d1                             // load first map in rotation
            /opt/ioquake3/baseq3/demo.cfg:
              content: !Sub |
                set g_gametype 0
                set fraglimit 20                    // frag limit for all modes (0 for no limit)
                set d1 "map q3dm7 ; set nextmap vstr d2"
                set d2 "map q3dm17 ; set nextmap vstr d3"
                set d3 "map q3tourney2 ; set nextmap vstr d1"
                vstr d1
            /opt/ioquake3/baseq3/varied.cfg:
              content: !Sub |
                set g_gametype 0
                set fraglimit 20                    // frag limit for all modes (0 for no limit)
                set d1 "map q3dm6 ; set nextmap vstr d2"
                set d2 "map q3dm7 ; set nextmap vstr d3"
                set d3 "map q3dm8 ; set nextmap vstr d4"
                set d4 "map q3dm13 ; set nextmap vstr d5"
                set d5 "map q3dm14 ; set nextmap vstr d6"
                set d6 "map q3dm15 ; set nextmap vstr d7"
                set d7 "map q3dm17 ; set nextmap vstr d1"
                vstr d1
            /opt/ioquake3/baseq3/custom.cfg:
              content: !Sub |
                set g_gametype 0
                set fraglimit 20                    // frag limit for all modes (0 for no limit)
                set d1 "map hub3aeroq3 ; set nextmap vstr d2"   // https://ws.q3df.org/map/hub3aeroq3/
                set d2 "map hub3tourney1 ; set nextmap vstr d3" // https://ws.q3df.org/map/hub3tourney1/
                set d3 "map cpm1a ; set nextmap vstr d4"        // https://ws.q3df.org/map/cpm1a
                set d4 "map ztn3dm1 ; set nextmap vstr d5"      // https://ws.q3df.org/map/ztn3dm1/
                set d5 "map alkdm06 ; set nextmap vstr d6"      // https://ws.q3df.org/map/alkdm06/
                set d6 "map bal3dm3 ; set nextmap vstr d1"      // https://ws.q3df.org/map/bal3dm3/
                vstr d1
            /opt/ioquake3/baseq3/custom2.cfg:
              content: !Sub |
                set g_gametype 0
                set fraglimit 20                    // frag limit for all modes (0 for no limit)
                set d1 "map hub3aeroq3 ; set nextmap vstr d2"   // https://ws.q3df.org/map/hub3aeroq3/
                set d2 "map hub3tourney1 ; set nextmap vstr d3" // https://ws.q3df.org/map/hub3tourney1/
                set d3 "map cpm1a ; set nextmap vstr d4"        // https://ws.q3df.org/map/cpm1a
                set d4 "map ztn3dm1 ; set nextmap vstr d5"      // https://ws.q3df.org/map/ztn3dm1/
                set d5 "map alkdm06 ; set nextmap vstr d6"      // https://ws.q3df.org/map/alkdm06/
                set d6 "map bal3dm3 ; set nextmap vstr d7"      // https://ws.q3df.org/map/bal3dm3/
                set d7 "map wvwq3dm7 ; set nextmap vstr d8"     // https://ws.q3df.org/map/wvwq3dm7/
                set d8 "map plutonians ; set nextmap vstr d9"   // https://ws.q3df.org/map/plutonians/
                set d9 "map simetrik ; set nextmap vstr d10"    // https://ws.q3df.org/map/simetrik/
                set d10 "map klzdeadly ; set nextmap vstr d11"  // https://ws.q3df.org/map/klzdeadly/
                set d11 "map charon3dm8 ; set nextmap vstr d12" // https://ws.q3df.org/map/charon3dm8/
                set d12 "map kamq3dm2 ; set nextmap vstr d13"   // https://ws.q3df.org/map/kamq3dm2/
                set d13 "map auh3dm1; set nextmap vstr d1"      // https://ws.q3df.org/map/auh3dm1/
                set d14 "map q3deck; set nextmap vstr d1"       // https://www.moddb.com/games/quake-iii-arena/addons/q3deck
                vstr d1
            /run/systemd/system/quake3@.service:
              content: !Sub |
                [Unit]
                Description=Quake3@%i
                After=network.target
                
                [Service]
                User=ec2-user
                Type=simple
                ExecStart=/opt/ioquake3/ioq3ded.arm64 +exec server%i.cfg
                KillMode=process
                Restart=on-failure
                StandardOutput=null
                StandardError=null
                
                [Install]
                WantedBy=multi-user.target
            /etc/systemd/journald.conf:
              content: !Sub |
                [Journal]
                SystemMaxUse=50M
            /usr/bin/icecon:
              source: 'https://github.com/icedream/icecon/releases/download/v1.0.0/icecon_linux_arm'
              mode: '000755'
    Properties:
      LaunchTemplateData: 
        KeyName: !Ref KeyName
        IamInstanceProfile:
          Name: !Ref InstanceProfile
        ImageId: !Ref AmiAlias
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
        # This is meant to be overridden by the ASG
        InstanceType: t4g.nano
        # The option below is really important! The alternative is for it to be unlimited, which might incur extra costs on top of the hourly rate.
        CreditSpecification:
          CpuCredits: unlimited
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeType: gp3
              VolumeSize: 2
              DeleteOnTermination: true
              Encrypted: false
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash -xe
            yum install -y vim htop aws-cli aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -s ${AWS::StackId} -r LaunchTemplate --region ${AWS::Region} || exit 1

            # Associate elastic IP manually to avoid the need for a load balancer
            aws configure set region ${AWS::Region}
            aws ec2 associate-address --instance-i `curl http://169.254.169.254/latest/meta-data/instance-id` --allocation-id  `aws ec2 describe-addresses --public-ips ${ElasticIp} --query 'Addresses[0].AllocationId' --output text`

            # Download ioquake3 from s3, but do pak0 separately to increase likelihood of it not flaking out
            aws s3 cp s3://${BucketName}/ /opt/ioquake3/ --exclude baseq3/pak0.pk3 --only-show-errors --recursive
            aws s3 cp s3://${BucketName}/baseq3/pak0.pk3 /opt/ioquake3/baseq3/pak0.pk3 --only-show-errors
            chmod +x /opt/ioquake3/ioq3ded.arm64

            # Restart journald so it picks up the 50M limit for log size
            systemctl restart systemd-journald

            # Start quake3 servers if a name for them has been passed in the params
            [ "${Server0Name}" != "" ] && systemctl enable --now quake3@0
            [ "${Server1Name}" != "" ] && systemctl enable --now quake3@1
Outputs:
  ElasticIp:
    Value: !Ref ElasticIp
    Description: The elastic IP to be associated with the instance
