install:
	sudo cp auto-mapper /usr/bin/auto-mapper
	sudo chmod 755 /usr/bin/auto-mapper
	sudo cp auto-mapper@.service /run/systemd/system/auto-mapper@.service
	sudo chmod 644 /run/systemd/system/auto-mapper@.service
